# Form implementation generated from reading ui file 'acc_info.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.block_button = QtWidgets.QPushButton(self.centralwidget)
        self.block_button.setGeometry(QtCore.QRect(280, 400, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.block_button.setFont(font)
        self.block_button.setObjectName("block_button")
        self.reh_scroll = QtWidgets.QScrollArea(self.centralwidget)
        self.reh_scroll.setGeometry(QtCore.QRect(280, 110, 261, 281))
        self.reh_scroll.setWidgetResizable(True)
        self.reh_scroll.setObjectName("reh_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 259, 279))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.reh_scroll.setWidget(self.scrollAreaWidgetContents)
        self.unblock_button = QtWidgets.QPushButton(self.centralwidget)
        self.unblock_button.setGeometry(QtCore.QRect(280, 440, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.unblock_button.setFont(font)
        self.unblock_button.setObjectName("unblock_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.block_button.setText(_translate("MainWindow", "Заблокировать"))
        self.unblock_button.setText(_translate("MainWindow", "Разблокировать"))
